// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PF_GerenciaEscolar.Data;

#nullable disable

namespace PF_GerenciaEscolar.Migrations
{
    [DbContext(typeof(PF_GerenciaEscolarDbContext))]
    [Migration("20240107222211_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.14")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("PF_GerenciaEscolar.Models.Administrador", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("AutenticacaoId")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nome")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("AutenticacaoId");

                    b.ToTable("Administradores");
                });

            modelBuilder.Entity("PF_GerenciaEscolar.Models.Aluno", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("AutenticacaoId")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nome")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Turma")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AutenticacaoId");

                    b.ToTable("Alunos");
                });

            modelBuilder.Entity("PF_GerenciaEscolar.Models.Autenticacao", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Cargo")
                        .HasColumnType("int");

                    b.Property<string>("Cpf")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Senha")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Autenticadores");
                });

            modelBuilder.Entity("PF_GerenciaEscolar.Models.Avaliacao", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Disciplina")
                        .HasColumnType("int");

                    b.Property<DateTime?>("Inicio")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("Prazo")
                        .HasColumnType("datetime2");

                    b.Property<string>("Titulo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Turma")
                        .HasColumnType("int");

                    b.Property<decimal?>("Valor")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("Avaliacoes");
                });

            modelBuilder.Entity("PF_GerenciaEscolar.Models.Nota", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("AlunoId")
                        .HasColumnType("int");

                    b.Property<int?>("AvaliacaoId")
                        .HasColumnType("int");

                    b.Property<decimal>("Valor")
                        .HasColumnType("decimal(18, 2)");

                    b.HasKey("Id");

                    b.HasIndex("AlunoId");

                    b.HasIndex("AvaliacaoId");

                    b.ToTable("Notas");
                });

            modelBuilder.Entity("PF_GerenciaEscolar.Models.Professor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("AutenticacaoId")
                        .HasColumnType("int");

                    b.Property<int>("Disciplina")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nome")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("AutenticacaoId");

                    b.ToTable("Professores");
                });

            modelBuilder.Entity("PF_GerenciaEscolar.Models.Administrador", b =>
                {
                    b.HasOne("PF_GerenciaEscolar.Models.Autenticacao", "Autenticacao")
                        .WithMany("Administradores")
                        .HasForeignKey("AutenticacaoId");

                    b.Navigation("Autenticacao");
                });

            modelBuilder.Entity("PF_GerenciaEscolar.Models.Aluno", b =>
                {
                    b.HasOne("PF_GerenciaEscolar.Models.Autenticacao", "Autenticacao")
                        .WithMany("Alunos")
                        .HasForeignKey("AutenticacaoId");

                    b.Navigation("Autenticacao");
                });

            modelBuilder.Entity("PF_GerenciaEscolar.Models.Nota", b =>
                {
                    b.HasOne("PF_GerenciaEscolar.Models.Aluno", null)
                        .WithMany("Notas")
                        .HasForeignKey("AlunoId");

                    b.HasOne("PF_GerenciaEscolar.Models.Avaliacao", null)
                        .WithMany("Notas")
                        .HasForeignKey("AvaliacaoId");
                });

            modelBuilder.Entity("PF_GerenciaEscolar.Models.Professor", b =>
                {
                    b.HasOne("PF_GerenciaEscolar.Models.Autenticacao", "Autenticacao")
                        .WithMany("Professores")
                        .HasForeignKey("AutenticacaoId");

                    b.Navigation("Autenticacao");
                });

            modelBuilder.Entity("PF_GerenciaEscolar.Models.Aluno", b =>
                {
                    b.Navigation("Notas");
                });

            modelBuilder.Entity("PF_GerenciaEscolar.Models.Autenticacao", b =>
                {
                    b.Navigation("Administradores");

                    b.Navigation("Alunos");

                    b.Navigation("Professores");
                });

            modelBuilder.Entity("PF_GerenciaEscolar.Models.Avaliacao", b =>
                {
                    b.Navigation("Notas");
                });
#pragma warning restore 612, 618
        }
    }
}
